ParadoxGameConverters/CK2ToEU4

CK2ToEU4/Data_Files/configurables/tag_mappings.txt

Updating titie_tags.txt

---

CK2ToEU4/Data_Files/blankMod/output/common/bookmarks/converter_bookmark_1444.txt
CK2ToEU4/Data_Files/blankMod/output/common/technologies/adm.txt
CK2ToEU4/Data_Files/blankMod/output/common/technologies/dip.txt
CK2ToEU4/Data_Files/blankMod/output/common/technologies/mil.txt
CK2ToEU4/Data_Files/blankMod/output/localisation/bookmark_conv_l_english.yml
CK2ToEU4/Data_Files/blankMod/output/localisation/bookmark_conv_l_french.yml
CK2ToEU4/Data_Files/blankMod/output/localisation/bookmark_conv_l_german.yml
CK2ToEU4/Data_Files/blankMod/output/localisation/bookmark_conv_l_spanish.yml
CK2ToEU4/Source/Common/CommonFunctions.cpp
CK2ToEU4/Source/Common/CommonFunctions.h
CK2ToEU4/Source/EU4World/Country/Country.cpp
CK2ToEU4/Source/EU4World/Country/CountryDetails.h
CK2ToEU4/Source/EU4World/Output/outCountry.cpp
CK2ToEU4/Source/EU4World/Output/outModFile.cpp

- monarchs start we a regnal number if country monarch names have rulers of their name
- 1444 boomark
- modded techs so earlier start dates don't go out of scope at 1444

Regnal numbers and 1444 bookmark

---

CK2ToEU4/Data_Files/configurables/tag_mappings.txt

Made changed based on Iohannes's feedback.

Fixed Tag Mapping

---

CK2ToEU4/Data_Files/blankMod/output/interface/added_countryreligionview.gui

- Added added_countryreligionview.gui from the base game converter to the interface folder.

Added GUI File

---

CK2ToEU4/Data_Files/configurables/culture_map.txt
CK2ToEU4/Source/EU4World/Province/EU4Province.cpp

- Pinging against ruler ck2 culture/religion in the specific province before pinging against tag culture/religion.
- Relevant for hordeland, mostly.
- Turkish mappings split in Central Asia

Turkish mappings and better province culture/religion assignment 

---

CK2ToEU4/Data_Files/configurables/culture_map.txt
CK2ToEU4/Source/EU4World/EU4World.cpp

- german in pommenaria to prussian
- better rounding for province dev calculations

Minor fixes

---

CK2ToEU4/Data_Files/blankMod/output/common/cultures/!.expanded_culture_groups.txt
CK2ToEU4/Data_Files/configurables/religion_map.txt
CK2ToEU4/Source/EU4World/Country/Country.cpp
CK2ToEU4/Source/EU4World/Country/Country.h
CK2ToEU4/Source/EU4World/EU4World.cpp
CK2ToEU4/Source/EU4World/EU4World.h

Remapping ex-burman cultures to tibetan_group.

Correctly split buddhism branches.

---

CK2ToEU4/Data_Files/blankMod/output/common/cultures/!.expanded_culture_groups.txt
CK2ToEU4/Data_Files/configurables/culture_map.txt

* italian differentiation
* slovene instead of carantanian
* greeks in syria
* slovak is west slavic
* dropping custom bosnian
* breton into cornish

1.30 culture alignment

---

CK2ToEU4/Data_Files/blankMod/output/common/ages/00_default.txt
CK2ToEU4/Data_Files/blankMod/output/common/cultures/!.expanded_culture_groups.txt
CK2ToEU4/Data_Files/blankMod/output/common/institutions/00_Core.txt
CK2ToEU4/Data_Files/configurables/culture_map.txt
CK2ToEU4/Data_Files/configurables/tag_mappings.txt

- Ages and Institutions updated
- Age bonuses expanded to allow for non-tag countries assuming they fill the requirements
- Holy Orders re-added to tag mappings
- Cultures now found in basegame EU4 have been removed to prevent overwriting basegame things.
- Carantanian now maps to Slovene.

Ages and Institutions

---

CK2ToEU4/Data_Files/blankMod/output/localisation/replace/converted_reforms_l_english.yml
CK2ToEU4/Data_Files/blankMod/output/localisation/replace/converted_reforms_l_french.yml
CK2ToEU4/Data_Files/blankMod/output/localisation/replace/converted_reforms_l_german.yml
CK2ToEU4/Data_Files/blankMod/output/localisation/replace/converted_reforms_l_spanish.yml
CK2ToEU4/Data_Files/configurables/government_map.txt
CK2ToEU4/Source/EU4World/Country/Country.cpp
CK2ToEU4/Source/EU4World/EU4World.cpp

- New Reforms Added
- Free Cities will be entirely determined by a seperate method
- Aristocratic now leads to English Monarchy rather than Despotism.

Reforms Have Been Updated for 1.30

---

CK2ToEU4/Data_Files/blankMod/output/common/institutions/00_Core.txt

History for Industry

---

CK2ToEU4/Data_Files/blankMod/output/decisions/ZZZ_new_decisions.txt
CK2ToEU4/Data_Files/configurables/province_mappings.txt

- Updated mapping for provinces, especially in Tartary and Indian Regions
- Reset admin tech to remove elctive monarchy to 15 to keep it close to 1600, which is when you can remove it as Poland/PLC.

Updated Province Mappings

---

CK2ToEU4/Data_Files/blankMod/output/decisions/ZZZ_new_decisions.txt

Manchu For Qing

---

CK2ToEU4/Source/Configuration/Configuration.cpp

That's what it's called on my system, always has been. Using Steam on Linux. Username on the forum is Silver Wizard.

Added "ck2" to the possible names for the executable.

---

CK2ToEU4/Source/EU4World/Country/Country.cpp

Noticed small error, fixed it.

Fixed a Small Error

---

CK2ToEU4/Source/EU4World/Country/Country.cpp
CK2ToEU4/Source/EU4World/EU4World.cpp
CK2ToEU4/Source/EU4World/Province/EU4Province.h

Annexed papal territories do not leave behind cores.
Dead nations do not get to have permaclaims.

Pope is indivisible.

---

CK2ToEU4/Data_Files/configurables/tag_mappings.txt

Lausitz to SOR

---

CK2ToEU4/Source/EU4World/Country/Country.cpp
CK2ToEU4/Source/EU4World/Country/Country.h
CK2ToEU4/Source/EU4World/EU4World.cpp

In case we're somehow annexing the emperor or electors, apply those flags onto the annexing tag.

Save HRE flags when annexing countries

---

CK2ToEU4/Source/CK2World/World.cpp
CK2ToEU4/Source/EU4World/EU4World.cpp

- prevent FCing of PU-ed countries.
- prevent PUs from gaining electorates.
- merge in aux titles before doing HRE stuff for more dev.

Fix country processing order

---

CK2ToEU4/Source/EU4World/EU4World.cpp

- provinces will now individually compete against each other once the global winner is chosen by same rules.
- also, how did this broken code ever work.

Fixing Battle Royale further.

---

CK2ToEU4/Data_Files/blankMod/output/common/ages/00_default.txt

Age of Reformation now triggers in 1594 if no Reformation ever happens

Age of Reformation

---

CK2ToEU4/Source/EU4World/EU4World.cpp
CK2ToEU4/Source/Mappers/ColorScraper/ColorScraper.cpp

- it got stuck on minusfully named baronies.
- also updating commons.

Fixing colorscraper

---

CK2ToEU4/Source/EU4World/EU4World.cpp

Yes, yes, I know they're small and stupid, but they are still part of the vanilla game.

Don't Burn The Vanilla Tribes

---

CK2ToEU4/Data_Files/blankMod/output/common/scripted_effects/ZZZ_enhanced_converter_scripted_effects.txt
CK2ToEU4/Data_Files/blankMod/output/events/!.ZZZ_added_fetishist_events.txt

- Small errors discovered while working on CK3 version.

Fetishist fixes

---

CK2ToEU4/Data_Files/configurables/province_mappings.txt

- mapped the seas, lakes, rivers, lefover wastelands for completion's sake.
- fixed minor missing mappings and mismaps.

updated mappings

---

CK2ToEU4/Data_Files/configurables/religion_map.txt
CK2ToEU4/Source/CK2World/Provinces/Province.h
CK2ToEU4/Source/CK2World/Provinces/Provinces.cpp
CK2ToEU4/Source/EU4World/EU4World.cpp
CK2ToEU4/Source/EU4World/Province/EU4Province.cpp
CK2ToEU4/Source/Mappers/ProvinceTitleMapper/ProvinceTitleMapper.cpp
CK2ToEU4Tests/CK2WorldTests/Provinces/ProvincesTests.cpp

- fix to malformed religion mappings
- Fix for loading Wonder ID 0 (Stonehedge)
- Fix for self-filtering of nonsense mappings (784 - Al 'Aqabah.txt)
- Related autofix to uncolonized Shahrazur

Several Fixes:

---

CK2ToEU4/Data_Files/blankMod/output/common/ages/00_default.txt
CK2ToEU4/Data_Files/blankMod/output/common/religions/!-1_religion.txt
CK2ToEU4/Data_Files/blankMod/output/common/religions/01_converted_religions.txt
CK2ToEU4/Data_Files/configurables/religion_map.txt

- Mappings to Protestant/Reformed have been removed and changed to other denominations.

Remember, No Protestant

---

CK2ToEU4/Data_Files/blankMod/output/decisions/ZZZ_converter_religion_decisions.txt
CK2ToEU4/Data_Files/blankMod/output/decisions/ZZZ_new_decisions.txt
CK2ToEU4/Data_Files/blankMod/output/localisation/new_converter_decisions_l_english.yml
CK2ToEU4/Data_Files/blankMod/output/localisation/new_converter_decisions_l_french.yml
CK2ToEU4/Data_Files/blankMod/output/localisation/new_converter_decisions_l_german.yml
CK2ToEU4/Data_Files/blankMod/output/localisation/new_converter_decisions_l_spanish.yml

Last of the not updated decision have been updated.

Decision Update

---

CK2ToEU4/Data_Files/blankMod/output/common/on_actions/ZZZ_added_on_actions.txt

- on_actions updated due to revelation that it is NOT additive.

On Actions Update

---

CK2ToEU4/Data_Files/blankMod/output/common/cultures/!.expanded_culture_groups.txt
CK2ToEU4/Data_Files/blankMod/output/common/cultures/!.new_culture_groups.txt
CK2ToEU4/Data_Files/configurables/culture_map.txt

Adds and maps cultures which are in the Imperator:Rome to CK II converter

Imperator:Rome to CK II culture mappings

---

CK2ToEU4/Data_Files/blankMod/output/events/!.ZZZ_added_fetishist_events.txt
CK2ToEU4/Data_Files/blankMod/output/interface/added_countryreligionview.gui

- Hopefully this will be our last bugfix until PDX updates again.

Final Bugfix

---

CK2ToEU4/Data_Files/configurables/tag_mappings.txt

Lesser Poland can no longer become Krakow and Kirghiz doesn't convert to Mongolia.

Various tag mapping corrections

---

CK2ToEU4/Data_Files/blankMod/output/common/religions/!-1_religion.txt

- Adds blessings to Zoroastrianism (Vanilla)

Zoroastrian Update

---

CK2ToEU4/Data_Files/blankMod/output/sound/ZZZ_converter_sounds.asset
CK2ToEU4/Data_Files/configurables/monuments_mappings.txt
CK2ToEU4/Data_Files/configurables/pagan_religions.txt
CK2ToEU4/Data_Files/configurables/reformation/oldPagans/03_pagan_religions.txt
CK2ToEU4/Source/CK2World/Provinces/Provinces.cpp
CK2ToEU4/Source/CK2World/Wonders/Wonder.cpp
CK2ToEU4/Source/CK2World/Wonders/Wonder.h
CK2ToEU4/Source/EU4World/EU4World.cpp
CK2ToEU4/Source/EU4World/Output/outMonument.cpp

- Crashes should be fixed by overwriting the Chinese_alliances.txt file.
- Added sound for pagan_religiojn_reformed
- Brahmins loyalty works properly for monuments now
- Pagan_religion_reformed now defined properly
- Wonders should no longer convert to monuments if they have no modifiers
- Monuments can no longer end up with more than 4 stages (0-3)

Crash Fix + Goodies

---

CK2ToEU4/Data_Files/configurables/culture_map.txt

- Fixes syntatical error in culture mapping

Culture Fix

---

CK2ToEU4/Source/EU4World/Country/Country.cpp

Don't set primary culture as accepted.

---

CK2ToEU4/Data_Files/blankMod/output/common/cultures/!.expanded_culture_groups.txt
CK2ToEU4/Data_Files/blankMod/output/localisation/replace/converted_cultures_l_english.yml
CK2ToEU4/Data_Files/blankMod/output/localisation/replace/converted_cultures_l_french.yml
CK2ToEU4/Data_Files/blankMod/output/localisation/replace/converted_cultures_l_german.yml
CK2ToEU4/Data_Files/blankMod/output/localisation/replace/converted_cultures_l_spanish.yml
CK2ToEU4/Data_Files/configurables/culture_map.txt

Norman is a culture that exists in vanilla EU IV, within the French group. Norse outside of Scandinavia is split like German, and the split for Norse culture in the French region is called Normand, named similarly to but different from the vanilla French-speaking Norman culture. 
Normally there wouldn't be an issue, but the vanilla Noman culture is called "normand" within the game's defines, meaning that the Norse-speaking Normand culture replaces the vanilla culture, causing Norman French to suddenly revert back to their old Norse ways upon converting from CK2.
This issue has been fixed by internally renaming Norse-split Normand culture to "normand_norse," allowing for both the French and Norse cultures to exist simultaneously

Norman Changes

---

CK2ToEU4/Data_Files/blankMod/output/localisation/replace/converted_cultures_l_english.yml
CK2ToEU4/Data_Files/blankMod/output/localisation/replace/converted_cultures_l_french.yml
CK2ToEU4/Data_Files/blankMod/output/localisation/replace/converted_cultures_l_german.yml
CK2ToEU4/Data_Files/blankMod/output/localisation/replace/converted_cultures_l_spanish.yml
CK2ToEU4/Source/EU4World/Output/outWorld.cpp

UTF-8 in Localisation output and adding BOM to culture localisations files

Localisation fixes

---

CK2ToEU4/Source/CK2World/Characters/Character.h
CK2ToEU4/Source/CK2World/World.cpp
CK2ToEU4/Source/EU4World/Country/Country.cpp
CK2ToEU4/Source/Mappers/MonumentsMapper/MonumentsMapping.cpp

-[fix for primary hre holder after shattering](https://github.com/ParadoxGameConverters/CK2ToEU4/commit/4fcc3cb1f7ffd07ea72e000d7794d0b283d91cf9)
-[fix for dry build triggers on monuments](https://github.com/ParadoxGameConverters/CK2ToEU4/commit/1c0a1aea27b00ca5a47b4803498804f7d0b94cc1)

Several fixes

---

CK2ToEU4/Data_Files/blankMod/output/localisation/replace/converted_reforms_l_english.yml
CK2ToEU4/Data_Files/blankMod/output/localisation/replace/converted_reforms_l_french.yml
CK2ToEU4/Data_Files/blankMod/output/localisation/replace/converted_reforms_l_german.yml
CK2ToEU4/Data_Files/blankMod/output/localisation/replace/converted_reforms_l_spanish.yml
CK2ToEU4/Source/EU4World/Country/Country.cpp

- Updated some government reforms.

Reform Update

---

CK2ToEU4/Data_Files/blankMod/output/localisation/replace/converted_cultures_l_german.yml

Removes double quote

---

CK2ToEU4/Data_Files/blankMod/output/common/government_reforms/ZZZ_enhanced_converter_reforms.txt
CK2ToEU4/Data_Files/blankMod/output/decisions/ZZZ_converter_formable_decisions.txt

Small Fixes

---

CK2ToEU4/Data_Files/configurables/sunset/history/provinces/880 - Pueblo.txt

- Province 880 is now Pueblo culture instead of no culture

Small SI Fix

---

CK2ToEU4/Data_Files/blankMod/output/common/cultures/!.expanded_culture_groups.txt

Fixed a bug that made bactrian provinces become no culture
It was present in the mappings but someone probably forgot to put it into the culture file

Bactria fix

---

CK2ToEU4/Data_Files/configurables/CleanSlate/culture_map.txt
CK2ToEU4/Data_Files/configurables/CleanSlate/religion_map.txt
CK2ToEU4/Data_Files/configurables/CleanSlate/tag_mappings.txt
CK2ToEU4/Data_Files/configurables/culture_map.txt
CK2ToEU4/Data_Files/configurables/religion_map.txt
CK2ToEU4/Data_Files/configurables/tag_mappings.txt

Updated culture, religion, & title mappings for mod compatibility.
Specifically, added mappings for Christian Immersion religions, Jewish Kings religions, some ACR religions, ACR gaulish culture split, & title mappings for Mesopotamia Reborn & ACR

Culture, Religion, & Title map updates

---

CK2ToEU4/Data_Files/configurables/dynamicInstitutions/ideas/00_basic_ideas.txt

- Updated Basic Ideas for 1.35
- Exploration updated so that hopefully only the region in which the Renaissance spawned should colonize until at least the 1600's.
- Expansion updated so that nations will expand into empty territories if no-one has done so by the mid 1700's.

Idea Update

---

CK2ToEU4/Data_Files/configurables/culture_map.txt

Karelian has been in the Scandinavian group since Lions of the North, if I'm not mistaken.

Update East Slavic culture mappings

---

CK2ToEU4/Data_Files/configurables/monuments_mappings.txt
CK2ToEU4/Source/Mappers/MonumentsMapper/BuildTriggerBuilder.cpp

- Updated Amphitheatre monument to accommodate the Roman Culture Group.

Romans Can Use the Amphitheatre

---

CK2ToEU4/Source/EU4World/Country/Country.cpp

Changes elective_monarchy to elective_monarchy_reform, changes Byzantium to have Byzantine govt.

Changes old polish elective monarchy to base elective monarchy

---

CK2ToEU4/Source/EU4World/Province/EU4Province.cpp

Allows East Asian cultures to use Chinese tech whilst still seeing themselves

Added Chinese tech group for east asian cultures

---

CK2ToEU4/Source/Configuration/Configuration.cpp
CK2ToEU4/Source/EU4World/Country/Country.cpp
CK2ToEU4/Source/EU4World/Diplomacy/Diplomacy.cpp
CK2ToEU4/Source/EU4World/EU4World.cpp
CK2ToEU4/Source/EU4World/Output/outMonument.cpp
CK2ToEU4/Source/EU4World/Output/outReligion.cpp
CK2ToEU4/Source/EU4World/Output/outWorld.cpp
CK2ToEU4/Source/EU4World/Province/EU4Province.cpp
CK2ToEU4/Source/Mappers/AfricanPassesMapper/AfricanPassesMapper.cpp
CK2ToEU4/Source/Mappers/DevWeightsMapper/DevWeightsMapper.cpp
CK2ToEU4/Source/Mappers/IAmHreMapper/IAmHreMapper.cpp
CK2ToEU4/Source/Mappers/LocalizationMapper/LocalizationMapper.cpp
CK2ToEU4/Source/Mappers/MonumentsMapper/MonumentsMapper.cpp
CK2ToEU4/Source/Mappers/PrimaryTagMapper/PrimaryTagMapper.cpp
CK2ToEU4/Source/Mappers/ProvinceMapper/ProvinceMapper.cpp
CK2ToEU4/Source/Mappers/ShatterEmpiresMapper/ShatterEmpiresMapper.cpp
CK2ToEU4/Source/Mappers/TitleTagMapper/TitleTagMapper.cpp
CK2ToEU4/Source/Mappers/VassalSplitoffMapper/VassalSplitoffMapper.cpp
CK2ToEU4/Source/main.cpp

Update to merged versions once available:

Update commons and simplify
